### PR TITLE
WIP Add FIR Model Setup Options

### PR DESCRIPTION
**Pull request by kastman**
Hi Michael, 

This small patch uses the FIR model already inside of Moss, and seems to be working for me, but I'm still testing. Any thoughts?

I'll add docs about hrf_params - we need at least nbasis I think. This edits the hrf class to take only kwargs, since some of the DoubleGamma args raise an error for the FIR hrf class. 

Best,
Erik

### CODE REVIEW

**Comment by mwaskom** [comment]
Sorry for the slow response.

Given the sorry state of automated testing in lyman, I'm generally averse to adding additional complexity, particularly when it's something that isn't going to be part of my normal workflow. I would worry about the downstream effects of these changes — the model code in particular has a lot of assumptions that this might break in weird ways.

I use FIR models all the time, but always on data extracted from ROIs. This makes a lot more sense to me — what do you do with all of the maps produced by univariate estimation of an FIR model? I also would think that the estimation of the model based on data from individual voxels is going to be quite poor.

**Comment by kastman** [comment]
I agree that you would want more testing before a full refactoring of the
model, but the changes I added slot in to the model assumptions alright; in
particular the use of `oversampling=1` uses all the same 'resampled'
infrastructure even though there is no resampling, following the FIR in
nipy. The main concept missing from the Moss model.py is the idea that the
actual basis functions/columns in the GLM may not be the 'conditions' as
they're given, but I edited the reporting to introspect the design matrix
itself to make this distinction allowable.

We use univariate voxelwise FIR modeling to enable some mixed event/block
models that break the GLM for standard HRF convolutions, and look at
contrasts of the FIR bf's that correspond to the expected peak - this gives
whole brain maps without assuming a specific form of the HRF. I was
skeptical like you when I first tried, but it works surprisingly well and
the parameter estimates are better & more stable than one would expect.
It's definitely an established tool that people use; happy to give you
references if you like.

If you're not comfortable including it I understand, but it will mean
cherry-picking these commits for me for each new release since we use this
for most of our models and tasks. I understand you don't want to add
anything that you won't use in a daily basis, but choosing different basis
functions seems, in my opinion, to be a fundamental part of modelling fMRI,
not feature creep?

Anything I can do (short of writing a whole test suite) that would make you
feel more comfortable? I've now tested this code base with both FIR and
double-gamma BF's, and the results (all the way through to group modeling)
look exactly like what I'd expect (notably, the double-gamma matches runs
with the stock 0.0.7 release).



On May 26, 2015, at 11:22 AM, Michael Waskom <notifications@github.com>
wrote:

Sorry for the slow response.

Given the sorry state of automated testing in lyman, I'm generally averse
to adding additional complexity, particularly when it's something that
isn't going to be part of my normal workflow. I would worry about the
downstream effects of these changes — the model code in particular has a
lot of assumptions that this might break in weird ways.

I use FIR models all the time, but always on data extracted from ROIs. This
makes a lot more sense to me — what do you do with all of the maps produced
by univariate estimation of an FIR model? I also would think that the
estimation of the model based on data from individual voxels is going to be
quite poor.

—
Reply to this email directly or view it on GitHub
<https://github.com/mwaskom/lyman/pull/63#issuecomment-105565064>.

**Comment by mwaskom** [comment]
Keep in mind that adding flexibility isn't just a matter of making sure that things look fine *now*; it's also a commitment to making sure that things will continue to look fine in the future. Without automated tests, that becomes very hard to verify, making it exponentially harder to change anything in the future (or to keep up with changes in the libraries that lyman depends on).

Also I should be clear that lyman isn't intended to cover all aspects of fMRI analysis, even the "fundamental" ones. The guiding principle, such as there is one, is to sacrifice some flexibility to gain the advantage of high automation. But it's not meant to compete at the level of SPM or FSL (or even Nipype) itself in terms of being a general purpose analysis environment.

I hope this doesn't come off as rude, but while I'm glad you are apparently finding lyman useful, I really can't commit to supporting other lab's workflows. I just don't have the bandwidth for it, and frankly, there is absolutely no incentive for me to. That's the unfortunate reality of current academic career considerations, as I imagine you're aware.

**Comment by kastman** [comment]
No worries and no offense taken; we're both pretty busy and that patch was certainly not prettiest thing I've ever written. Open code is open code and this is what forks are for; I appreciate that you've put it out there, and maybe if either one of us gets to writing a proper integration test suite (and refactoring the lyman internals) then it will be a better fit.

**Pull request closed without merging**
